/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  GetNetworkActivities200,
  GetNetworkActivitiesParams,
  GetUserActivities200,
  GetUserActivitiesParams
} from './endpoints.schemas';

import { axiosInstance } from './axios';





/**
 * Get user activities
 */
export const getUserActivities = (
    userId: string,
    params?: GetUserActivitiesParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<GetUserActivities200>(
      {url: `/user/${userId}/activities`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetUserActivitiesQueryKey = (userId: string,
    params?: GetUserActivitiesParams,) => {
    return [`/user/${userId}/activities`, ...(params ? [params]: [])] as const;
    }

    
export const getGetUserActivitiesInfiniteQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(userId: string,
    params?: GetUserActivitiesParams, options?: { query?:UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivities>>> = ({ signal }) => getUserActivities(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserActivitiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivities>>>
export type GetUserActivitiesInfiniteQueryError = unknown



export function useGetUserActivitiesInfinite<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>, }

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserActivitiesInfiniteQueryOptions(userId,params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetUserActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(userId: string,
    params?: GetUserActivitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivities>>> = ({ signal }) => getUserActivities(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivities>>>
export type GetUserActivitiesQueryError = unknown



export function useGetUserActivities<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserActivitiesQueryOptions(userId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetUserActivitiesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(userId: string,
    params?: GetUserActivitiesParams, options?: { query?:UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivities>>> = ({ signal }) => getUserActivities(userId,params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserActivitiesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivities>>>
export type GetUserActivitiesSuspenseQueryError = unknown



export function useGetUserActivitiesSuspense<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserActivitiesSuspenseQueryOptions(userId,params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Delete user activity
 */
export const deleteUserActivity = (
    activityId: string,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `/user/activities/${activityId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext> => {
    
const mutationKey = ['deleteUserActivity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserActivity>>, {activityId: string}> = (props) => {
          const {activityId} = props ?? {};

          return  deleteUserActivity(activityId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserActivityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserActivity>>>
    
    export type DeleteUserActivityMutationError = unknown

    export const useDeleteUserActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserActivity>>,
        TError,
        {activityId: string},
        TContext
      > => {

      const mutationOptions = getDeleteUserActivityMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get network activities
 */
export const getNetworkActivities = (
    params: GetNetworkActivitiesParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<GetNetworkActivities200>(
      {url: `/network/activities`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetNetworkActivitiesQueryKey = (params: GetNetworkActivitiesParams,) => {
    return [`/network/activities`, ...(params ? [params]: [])] as const;
    }

    
export const getGetNetworkActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(params: GetNetworkActivitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNetworkActivitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNetworkActivities>>> = ({ signal }) => getNetworkActivities(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNetworkActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getNetworkActivities>>>
export type GetNetworkActivitiesQueryError = unknown



export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNetworkActivitiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetNetworkActivitiesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(params: GetNetworkActivitiesParams, options?: { query?:UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNetworkActivitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNetworkActivities>>> = ({ signal }) => getNetworkActivities(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNetworkActivitiesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getNetworkActivities>>>
export type GetNetworkActivitiesSuspenseQueryError = unknown



export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNetworkActivitiesSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



